"""Added the timestamp column to the users table

Revision ID: 2ea17709c746
Revises: 
Create Date: 2022-03-14 12:52:33.001436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ea17709c746'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('timestamp', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('last_login', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_login')
    op.drop_column('users', 'timestamp')
    # ### end Alembic commands ###
